# add-autostart-task.ps1
# Creates a Windows scheduled task to auto-start opencode serve on user logon.
#
# Usage (Run PowerShell as Administrator):
#   .\add-autostart-task.ps1 -Workspace "D:\Vibecoding\Opencode_Project" -Password "your-password"
#
# Optional:
#   -Username    Basic Auth username (default: opencode)
#   -Port        Port number (default: 4096)
#   -TaskName    Scheduled task name (default: OpencodeServeAutostart)

param(
  [Parameter(Mandatory=$true)]
  [string]$Workspace,

  [Parameter(Mandatory=$true)]
  [string]$Password,

  [string]$Username = "opencode",

  [int]$Port = 4096,

  [string]$TaskName = "OpencodeServeAutostart"
)

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Generate a wrapper batch file with env vars (gitignored, contains password)
$wrapperBat = Join-Path $scriptDir "start-autostart.bat"
$wrapperContent = @"
@echo off
REM Auto-generated by add-autostart-task.ps1. Do not commit to git.
set OPENCODE_WORKSPACE=$Workspace
set OPENCODE_SERVER_USERNAME=$Username
set OPENCODE_SERVER_PASSWORD=$Password
set OPENCODE_PORT=$Port
call "%~dp0start-serve.bat"
"@
$wrapperContent | Out-File -FilePath $wrapperBat -Encoding ASCII

Write-Host "[INFO] Wrapper script created: $wrapperBat"

# Remove existing task if present
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
  Write-Host "[INFO] Task already exists, removing..."
  Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

$action = New-ScheduledTaskAction -Execute $wrapperBat -WorkingDirectory $scriptDir
$trigger = New-ScheduledTaskTrigger -AtLogOn
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited
$settings = New-ScheduledTaskSettingsSet `
  -AllowStartIfOnBatteries `
  -DontStopIfGoingOnBatteries `
  -StartWhenAvailable `
  -RestartCount 3 `
  -RestartInterval (New-TimeSpan -Minutes 1) `
  -ExecutionTimeLimit (New-TimeSpan -Hours 0)

try {
  Register-ScheduledTask -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Principal $principal `
    -Settings $settings `
    -Description "Auto-start opencode serve (Feishu phone bot)" `
    | Out-Null

  Write-Host "[OK] Task '$TaskName' created successfully" -ForegroundColor Green
  Get-ScheduledTask -TaskName $TaskName | Format-List TaskName, State, Description
  Write-Host ""
  Write-Host "Task will run on next logon. Test manually: & '$wrapperBat'" -ForegroundColor Cyan
  Write-Host ""
  Write-Host "[NOTE] $wrapperBat contains password, ignored by .gitignore" -ForegroundColor DarkGray
}
catch {
  Write-Host "[ERROR] Failed to create task: $_" -ForegroundColor Red
  exit 1
}
